version: '3.7'

services:
  server:
    build:
      context: ./apps/OpenSignServer
      dockerfile: Dockerfile
    image: opensignserver-image
    container_name: OpenSignServer-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./data/OpenSignServer/:/usr/src/app
      - ./data/node_modules:/usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - tunnel
  mongo:
    build:
      context: ./apps/mongo
      dockerfile: Dockerfile
    container_name: mongo-container
    image: opensign-mongo
    volumes:
      - ./data/mongo/data:/data/db
      - ./data/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - tunnel
  client:
    build:
      context: ./apps/OpenSign
      dockerfile: Dockerfile
    image: opensign-image
    container_name: OpenSign-container
    command: npm start
    env_file: .env
    volumes:
      - ./data/OpenSign/:/usr/app
      - ./data/node_modules:/usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - tunnel

networks:
    tunnel:
        external: true
