name: Build and push main image

on:
  push:
    branches: 
    - main
    - staging

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build  -f apps/OpenSign/Dockerfile . --tag ghcr.io/baldator/opensign:${GITHUB_REF##*/}
          docker push ghcr.io/baldator/opensign:${GITHUB_REF##*/}
          docker build  -f apps/OpenSignServer/Dockerfile . --tag ghcr.io/baldator/opensign-server:${GITHUB_REF##*/}
          docker push ghcr.io/baldator/opensign-server:${GITHUB_REF##*/}
          docker build  -f apps/mongo/Dockerfile . --tag ghcr.io/baldator/opensign-mongo:${GITHUB_REF##*/}
          docker push ghcr.io/baldator/opensign-mongo:${GITHUB_REF##*/}
